name: Docker registry

on: [push]

jobs:
  github:
    runs-on: ubuntu-latest 
    
    container: openjdk:11-jdk
     
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: tp_devops
          POSTGRES_USER: tp_devops
          POSTGRES_DB: tp_devops
        
    steps:
      - name: Git clone
        uses: actions/checkout@v1
        
      - name: Test jar
        run: ./gradlew check -Pdatabase.url=postgres/tp_devops
        
      - name: Create jar
        if: success()
        run: ./gradlew assemble
        
      - name: Build and push Docker images
        if: success()
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags:  guillaumeclement/tp_devops:latest

          
          
